theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  summary:
    position: hero
  search:
    active: false  
  logo:
    header: "/assets/images/logo-blanc.svg"
    footer: "/assets/images/logo.svg"
  breadcrumb:
    position: hero-end
