theme: osuny
_merge: deep
params:
  menu:
    primary:
      level_2:
        title:
          active: true
  summary:
    position: hero
  search:
    active: false  
  logo:
    header: "/assets/images/logo-blanc.svg"
    footer: "/assets/images/logo.svg"
  breadcrumb:
    position: hero-end
